Repository TwinDragonLikesLatte/Portal4U, pull requests merged in 2022-02, with the labels that each got.

#2 Feat(NFTAction): Add 패키지 구조 파일 추가
  src/main/java/com/test/portal4u/NFT/NFTAction/AcEndDTO.java
  src/main/java/com/test/portal4u/NFT/NFTAction/AcNowDTO.java
  src/main/java/com/test/portal4u/NFT/NFTAction/AcProdDTO.java
  src/main/java/com/test/portal4u/NFT/NFTAction/AcStartDTO.java
  src/main/java/com/test/portal4u/NFT/NFTAction/ActionController.java
  src/main/java/com/test/portal4u/NFT/NFTAction/ActionDAO.java
  src/main/java/com/test/portal4u/NFT/NFTAction/ActionDAOImpl.java
  src/main/java/com/test/portal4u/NFT/NFTAction/ActionService.java
  src/main/java/com/test/portal4u/NFT/NFTAction/ActionServiceImpl.java
  src/main/java/com/test/portal4u/NFT/NFTAction/mapper/action.xml
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardController.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardDAO.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardDAOImpl.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardDTO.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardService.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardServiceImpl.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/mapper/nftboard.xml
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/NFT/Board/add.jsp
  src/main/webapp/WEB-INF/views/NFT/Board/del.jsp
  src/main/webapp/WEB-INF/views/NFT/Board/edit.jsp
  src/main/webapp/WEB-INF/views/NFT/Board/list.jsp
  src/main/webapp/WEB-INF/views/NFT/Board/view.jsp
  src/main/webapp/WEB-INF/views/NFT/NFTAction/admin.jsp
  src/main/webapp/WEB-INF/views/NFT/NFTAction/main.jsp
  src/main/webapp/WEB-INF/views/NFT/NFTAction/mainAdd.jsp
  src/main/webapp/WEB-INF/views/NFT/layout/borad.jsp
  src/main/webapp/WEB-INF/views/NFT/layout/main.jsp
  src/main/webapp/resources/css/NFTAction/reset.css
  src/main/webapp/resources/css/NFTAction/styles.css
  src/main/webapp/resources/images/NFTAction/NFT.jpeg
  src/main/webapp/resources/images/NFTAction/Nyan cat.gif
  src/main/webapp/resources/images/NFTAction/ad.png
  src/main/webapp/resources/images/NFTAction/back.png
  src/main/webapp/resources/images/NFTAction/beach.png
  src/main/webapp/resources/images/NFTAction/내일 경매.png
  src/main/webapp/resources/images/NFTAction/이전경매.png
Labels: 온라인경매

#5 Feat(TraditionalLiquor): Add Package structure and files
  src/main/java/com/test/portal4u/TraditionalLiquor/Board/BoardController.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Board/BoardDAO.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Board/BoardDAOImpl.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Board/BoardDTO.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Board/BoardService.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Board/BoardServiceImpl.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Board/mapper/board.xml
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductController.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductDAO.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductDAOImpl.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductDTO.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductExplainDTO.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductImgDTO.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductInfoDTO.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductService.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductSeviceImpl.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/mapper/product.xml
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Board/add.jsp
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Board/del.jsp
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Board/edit.jsp
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Board/list.jsp
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Board/view.jsp
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Product/detail.jsp
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Product/main.jsp
Labels: 전통주

#8 Feat(TraditionalLiquor) : Add MainFrame
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductController.java
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Product/main.jsp
  src/main/webapp/resources/css/TraditionalLiquor/main.css
  src/main/webapp/resources/css/TraditionalLiquor/reset.css
  src/main/webapp/resources/images/TraditionalLiquor/divide_1.png
  src/main/webapp/resources/images/TraditionalLiquor/main_text.png
Labels: 전통주

#9 Feat(Member): Add member login, join
  sql/member.sql
  src/main/java/com/test/portal4u/mapper/member.xml
  src/main/java/com/test/portal4u/member/LoginInfo.java
  src/main/java/com/test/portal4u/member/MemberController.java
  src/main/java/com/test/portal4u/member/MemberDAO.java
  src/main/java/com/test/portal4u/member/MemberDAOImpl.java
  src/main/java/com/test/portal4u/member/MemberDTO.java
  src/main/java/com/test/portal4u/member/MemberService.java
  src/main/java/com/test/portal4u/member/MemberServiceImpl.java
  src/main/webapp/WEB-INF/mybatis.xml
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/member/join.jsp
  src/main/webapp/WEB-INF/views/member/login.jsp
  src/main/webapp/WEB-INF/views/member/member.jsp
Labels: 공통

#10 Feat(Tour): Add Package and files
  .classpath
  .gitignore
  .project
  src/branchTest
  src/main/java/com/test/portal4u/Tour/Board/BoardController.java
  src/main/java/com/test/portal4u/Tour/Board/BoardDAO.java
  src/main/java/com/test/portal4u/Tour/Board/BoardDAOImpl.java
  src/main/java/com/test/portal4u/Tour/Board/BoardDTO.java
  src/main/java/com/test/portal4u/Tour/Board/BoardService.java
  src/main/java/com/test/portal4u/Tour/Board/BoardServiceImpl.java
  src/main/java/com/test/portal4u/Tour/Board/mapper/board.xml
  src/main/java/com/test/portal4u/Tour/Place/PlaceController.java
  src/main/java/com/test/portal4u/Tour/Place/PlaceDAO.java
  src/main/java/com/test/portal4u/Tour/Place/PlaceDAOImpl.java
  src/main/java/com/test/portal4u/Tour/Place/PlaceDTO.java
  src/main/java/com/test/portal4u/Tour/Place/PlaceService.java
  src/main/java/com/test/portal4u/Tour/Place/PlaceServiceImpl.java
  src/main/java/com/test/portal4u/Tour/Place/mapper/place.xml
Labels: 여행지소개

#11 Feat(Tour): Add Package and files
  src/main/webapp/WEB-INF/views/Tour/Board/add.jsp
  src/main/webapp/WEB-INF/views/Tour/Board/del.jsp
  src/main/webapp/WEB-INF/views/Tour/Board/edit.jsp
  src/main/webapp/WEB-INF/views/Tour/Board/list.jsp
  src/main/webapp/WEB-INF/views/Tour/Board/view.jsp
  src/main/webapp/WEB-INF/views/Tour/Place/desc.jsp
  src/main/webapp/WEB-INF/views/Tour/layout/board.jsp
  src/main/webapp/WEB-INF/views/Tour/layout/main.jsp
Labels: 여행지소개

#13 웹소켓 stomp 로직, 그룹 api, 채널 api, 페이지 레이아웃
  pom.xml
  sql/alliance/group.sql
  src/main/java/com/test/portal4u/alliance/AllianceController.java
  src/main/java/com/test/portal4u/alliance/channel/ChannelController.java
  src/main/java/com/test/portal4u/alliance/channel/ChannelDAOImpl.java
  src/main/java/com/test/portal4u/alliance/channel/ChannelDTO.java
  src/main/java/com/test/portal4u/alliance/channel/ChannelService.java
  src/main/java/com/test/portal4u/alliance/channel/ChannelServiceImpl.java
  src/main/java/com/test/portal4u/alliance/channel/ChannelroomDAO.java
  src/main/java/com/test/portal4u/alliance/group/GroupController.java
  src/main/java/com/test/portal4u/alliance/group/GroupDAO.java
  src/main/java/com/test/portal4u/alliance/group/GroupDAOImpl.java
  src/main/java/com/test/portal4u/alliance/group/GroupDTO.java
  src/main/java/com/test/portal4u/alliance/group/GroupJoinDTO.java
  src/main/java/com/test/portal4u/alliance/group/GroupService.java
  src/main/java/com/test/portal4u/alliance/group/GroupServiceImpl.java
  src/main/java/com/test/portal4u/alliance/websocket/ChatController.java
  src/main/java/com/test/portal4u/alliance/websocket/WebSocketConfig.java
  src/main/java/com/test/portal4u/mapper/channel.xml
  src/main/java/com/test/portal4u/mapper/group.xml
  src/main/webapp/WEB-INF/mybatis.xml
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/alliance/alliance.jsp
  src/main/webapp/WEB-INF/views/alliance/channel.jsp
  src/main/webapp/WEB-INF/views/alliance/chatContainer.jsp
  src/main/webapp/WEB-INF/views/alliance/group.jsp
  src/main/webapp/WEB-INF/views/alliance/header.jsp
  src/main/webapp/WEB-INF/views/alliance/myinfo.jsp
  src/main/webapp/WEB-INF/views/alliance/people.jsp
  src/main/webapp/resources/js/jquery.serializeObject.js
Labels: 그룹채팅

#14 Feat(Alliance): Add design alliance
  src/main/webapp/WEB-INF/views/alliance/alliance.jsp
  src/main/webapp/WEB-INF/views/alliance/chatContainer.jsp
  src/main/webapp/WEB-INF/views/alliance/group.jsp
  src/main/webapp/WEB-INF/views/alliance/myinfo.jsp
  src/main/webapp/WEB-INF/views/alliance/people.jsp
Labels: 그룹채팅

#16 Feat(TraditionalLiquor) : Add Modal and list
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductController.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductDAO.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductDAOImpl.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductDTO.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductExplainDTO.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductService.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductServiceImpl.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/ProductSeviceImpl.java
  src/main/java/com/test/portal4u/TraditionalLiquor/Product/mapper/product.xml
  src/main/java/com/test/portal4u/mapper/tlproduct.xml
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Product/main.jsp
  src/main/webapp/resources/css/TraditionalLiquor/main.css
  src/main/webapp/resources/images/TraditionalLiquor/backhwa.png
  src/main/webapp/resources/images/TraditionalLiquor/beoulsan.png
  src/main/webapp/resources/images/TraditionalLiquor/gompyo.png
  src/main/webapp/resources/images/TraditionalLiquor/man.png
  src/main/webapp/resources/images/TraditionalLiquor/map.png
  src/main/webapp/resources/images/TraditionalLiquor/miin.png
  src/main/webapp/resources/images/TraditionalLiquor/people.png
  src/main/webapp/resources/images/TraditionalLiquor/sejong.png
  src/main/webapp/resources/images/TraditionalLiquor/tiger.png
  src/main/webapp/resources/images/TraditionalLiquor/warning.png
  src/main/webapp/resources/images/TraditionalLiquor/warningmodal.png
  src/main/webapp/resources/images/TraditionalLiquor/water.jpg
  src/main/webapp/resources/images/TraditionalLiquor/yangji.png
Labels: 전통주

#17 Feature/news letter front
  src/main/java/com/test/portal4u/newsletter/subscribe/SubscribeController.java
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/newsletter/inc/header.jsp
  src/main/webapp/WEB-INF/views/newsletter/layout/newsletterMain.jsp
  src/main/webapp/WEB-INF/views/newsletter/layout/subscribeMain.jsp
  src/main/webapp/WEB-INF/views/newsletter/main/list.jsp
  src/main/webapp/WEB-INF/views/newsletter/main/member.jsp
  src/main/webapp/WEB-INF/views/newsletter/main/statistics.jsp
  src/main/webapp/WEB-INF/views/newsletter/main/write.jsp
  src/main/webapp/WEB-INF/views/newsletter/subscribe/subscribe.jsp
  src/main/webapp/WEB-INF/views/newsletter/subscribe/subscribeok.jsp
  src/main/webapp/resources/css/newsletter/component/checkbox.css
  src/main/webapp/resources/css/newsletter/component/header.css
  src/main/webapp/resources/css/newsletter/component/modal.css
  src/main/webapp/resources/css/newsletter/component/reset.css
  src/main/webapp/resources/css/newsletter/component/variables.css
  src/main/webapp/resources/css/newsletter/screen/list.css
  src/main/webapp/resources/css/newsletter/screen/member.css
  src/main/webapp/resources/css/newsletter/screen/statistics.css
  src/main/webapp/resources/css/newsletter/screen/subscribe.css
  src/main/webapp/resources/css/newsletter/screen/write.css
  src/main/webapp/resources/css/newsletter/styles.css
Labels: 뉴스레터

#18 Feature/news letter subscribe
  src/main/java/com/test/portal4u/mapper/subscribe.xml
  src/main/java/com/test/portal4u/newsletter/subscribe/PreperGenreDTO.java
  src/main/java/com/test/portal4u/newsletter/subscribe/SubscribeController.java
  src/main/java/com/test/portal4u/newsletter/subscribe/SubscribeDAO.java
  src/main/java/com/test/portal4u/newsletter/subscribe/SubscribeDAOImpl.java
  src/main/java/com/test/portal4u/newsletter/subscribe/SubscribeService.java
  src/main/java/com/test/portal4u/newsletter/subscribe/SubscribeServiceImpl.java
  src/main/java/com/test/portal4u/newsletter/subscribe/SubscriberDTO.java
  src/main/webapp/WEB-INF/mybatis.xml
  src/main/webapp/WEB-INF/views/newsletter/subscribe/subscribe.jsp
  src/main/webapp/WEB-INF/views/newsletter/subscribe/subscribeok.jsp
  src/main/webapp/resources/css/newsletter/component/checkbox.css
  src/main/webapp/resources/css/newsletter/screen/subscribe.css
Labels: 뉴스레터

#22 Feature/news letter write
  src/main/java/com/test/portal4u/mapper/pitchfork.xml
  src/main/java/com/test/portal4u/newsletter/subscribe/SubscribeController.java
  src/main/java/com/test/portal4u/newsletter/write/NewsletterDTO.java
  src/main/java/com/test/portal4u/newsletter/write/PitchforkDTO.java
  src/main/java/com/test/portal4u/newsletter/write/TranslateAPI.java
  src/main/java/com/test/portal4u/newsletter/write/WriteController.java
  src/main/java/com/test/portal4u/newsletter/write/WriteDAO.java
  src/main/java/com/test/portal4u/newsletter/write/WriteDAOImpl.java
  src/main/java/com/test/portal4u/newsletter/write/WriteService.java
  src/main/java/com/test/portal4u/newsletter/write/WriteServiceImpl.java
  src/main/webapp/WEB-INF/mybatis.xml
  src/main/webapp/WEB-INF/views/newsletter/main/list.jsp
  src/main/webapp/WEB-INF/views/newsletter/main/write.jsp
  src/main/webapp/resources/css/newsletter/screen/write.css
Labels: 뉴스레터

#27 Feature/news letter list
  src/main/java/com/test/portal4u/mapper/newsletter.xml
  src/main/java/com/test/portal4u/newsletter/post/PostController.java
  src/main/java/com/test/portal4u/newsletter/post/PostDAO.java
  src/main/java/com/test/portal4u/newsletter/post/PostDAOImpl.java
  src/main/java/com/test/portal4u/newsletter/post/PostDTO.java
  src/main/java/com/test/portal4u/newsletter/post/PostService.java
  src/main/java/com/test/portal4u/newsletter/post/PostServiceImpl.java
  src/main/java/com/test/portal4u/newsletter/subscribe/SubscribeController.java
  src/main/webapp/WEB-INF/mybatis.xml
  src/main/webapp/WEB-INF/views/newsletter/main/list.jsp
  src/main/webapp/resources/css/newsletter/component/modal.css
  src/main/webapp/resources/css/newsletter/screen/list.css
Labels: 뉴스레터

#28 Feature/news letter hardcoding
  src/main/webapp/WEB-INF/views/newsletter/inc/header.jsp
  src/main/webapp/WEB-INF/views/newsletter/main/member.jsp
  src/main/webapp/WEB-INF/views/newsletter/main/statistics.jsp
  src/main/webapp/resources/css/newsletter/component/header.css
  src/main/webapp/resources/css/newsletter/screen/member.css
Labels: 뉴스레터

#29 Feature/news letter delete
  src/main/java/com/test/portal4u/mapper/newsletter.xml
  src/main/java/com/test/portal4u/newsletter/post/PostController.java
  src/main/java/com/test/portal4u/newsletter/post/PostDAO.java
  src/main/java/com/test/portal4u/newsletter/post/PostDAOImpl.java
  src/main/java/com/test/portal4u/newsletter/post/PostService.java
  src/main/java/com/test/portal4u/newsletter/post/PostServiceImpl.java
  src/main/webapp/WEB-INF/views/newsletter/main/list.jsp
  src/main/webapp/resources/css/newsletter/component/modal.css
Labels: 뉴스레터

#31 Feature/tl design
  sql/TraditionalLiquor/script.sql
  src/main/java/com/test/portal4u/TraditionalLiquor/Board/TLBoardController.java
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Board/add.jsp
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Board/list.jsp
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Board/view.jsp
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Product/main.jsp
  src/main/webapp/resources/css/TraditionalLiquor/main.css
  src/main/webapp/resources/images/TraditionalLiquor/bling.png
  src/main/webapp/resources/images/TraditionalLiquor/budea.jpg
  src/main/webapp/resources/images/TraditionalLiquor/drop.png
  src/main/webapp/resources/images/TraditionalLiquor/egg.jpg
  src/main/webapp/resources/images/TraditionalLiquor/first.png
  src/main/webapp/resources/images/TraditionalLiquor/fish.jpg
  src/main/webapp/resources/images/TraditionalLiquor/gimbab.jpg
  src/main/webapp/resources/images/TraditionalLiquor/honghap.jpg
  src/main/webapp/resources/images/TraditionalLiquor/love.png
  src/main/webapp/resources/images/TraditionalLiquor/omirose.png
  src/main/webapp/resources/images/TraditionalLiquor/pajeon.jpg
  src/main/webapp/resources/images/TraditionalLiquor/pigfoot.jpg
  src/main/webapp/resources/images/TraditionalLiquor/potato.jpg
  src/main/webapp/resources/images/TraditionalLiquor/pungjeong.png
  src/main/webapp/resources/images/TraditionalLiquor/rice.jpg
  src/main/webapp/resources/images/TraditionalLiquor/sinabro.png
Labels: 전통주

#32 featur/TLSubscribe
  src/main/webapp/WEB-INF/views/TraditionalLiquor/Product/main.jsp
  src/main/webapp/resources/css/TraditionalLiquor/main.css
Labels: 전통주

#33 Feat(NFTAcion): Add 각종 기능 추가
  sql/NTFAction/script.sql
  src/main/java/com/test/portal4u/NFT/NFTAction/ActionController.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardController.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardDAO.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardDAOImpl.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardDTO.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardService.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTBoardServiceImpl.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/NFTFreeBoardDTO.java
  src/main/java/com/test/portal4u/NFT/NFTBoard/mapper/nftboard.xml
  src/main/java/com/test/portal4u/mapper/nftboard.xml
  src/main/webapp/WEB-INF/mybatis.xml
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/tiles.xml
  src/main/webapp/WEB-INF/views/NFT/Admin/admin.jsp
  src/main/webapp/WEB-INF/views/NFT/Board/add.jsp
  src/main/webapp/WEB-INF/views/NFT/Board/board.jsp
  src/main/webapp/WEB-INF/views/NFT/Board/list.jsp
  src/main/webapp/WEB-INF/views/NFT/Board/view.jsp
  src/main/webapp/WEB-INF/views/NFT/NFTAction/main.jsp
  src/main/webapp/WEB-INF/views/NFT/inc/action_content.jsp
  src/main/webapp/WEB-INF/views/NFT/inc/action_title.jsp
  src/main/webapp/WEB-INF/views/NFT/inc/in_action.jsp
  src/main/webapp/WEB-INF/views/NFT/inc/logo.jsp
Labels: 온라인경매

#35 Feature/news letter detail
  src/main/java/com/test/portal4u/mapper/pitchfork.xml
  src/main/webapp/WEB-INF/views/newsletter/main/list.jsp
  src/main/webapp/resources/css/newsletter/screen/list.css
  src/main/webapp/resources/css/newsletter/screen/write.css
Labels: 뉴스레터

#36 feature/main
  src/main/webapp/WEB-INF/views/home/home.jsp
  src/main/webapp/resources/css/home/assets/NFT.png
  src/main/webapp/resources/css/home/assets/newsletter.png
  src/main/webapp/resources/css/home/assets/sazo.png
  src/main/webapp/resources/css/home/assets/title.png
  src/main/webapp/resources/css/home/reset.css
  src/main/webapp/resources/css/home/styles.css
Labels: 공통

#38 Feat(Alliance): Add Channel dummy script
  sql/alliance/channel.sql
Labels: 그룹채팅

#39 feature/newsLetterSQL
  sql/newsletter/script.sql
Labels: 뉴스레터
